import { NextRequest, NextResponse } from "next/server";
import {
  extractSpotifyTrackUri,
  getCookieTokenData,
  getSpotifyEnv,
  isAccessTokenExpired,
  refreshAccessToken,
} from "@/lib/spotify-oauth";
import { writeApiLogFile } from "@/lib/request-log";

type CreatePlaylistBody = {
  name?: string;
  description?: string;
  trackUrls?: string[];
  isPublic?: boolean;
};

function setTokenCookies(
  response: NextResponse,
  params: { accessToken: string; refreshToken?: string; expiresIn: number },
) {
  const expiresAt = Date.now() + params.expiresIn * 1000;

  response.cookies.set("spotify_access_token", params.accessToken, {
    httpOnly: true,
    sameSite: "lax",
    secure: process.env.NODE_ENV === "production",
    maxAge: params.expiresIn,
    path: "/",
  });

  response.cookies.set("spotify_token_expires_at", String(expiresAt), {
    httpOnly: true,
    sameSite: "lax",
    secure: process.env.NODE_ENV === "production",
    maxAge: params.expiresIn,
    path: "/",
  });

  if (params.refreshToken) {
    response.cookies.set("spotify_refresh_token", params.refreshToken, {
      httpOnly: true,
      sameSite: "lax",
      secure: process.env.NODE_ENV === "production",
      maxAge: 60 * 60 * 24 * 30,
      path: "/",
    });
  }
}

async function getValidAccessToken(req: NextRequest) {
  const { clientId, clientSecret } = getSpotifyEnv();
  const { accessToken, refreshToken, expiresAt } = getCookieTokenData(req);

  if (accessToken && !isAccessTokenExpired(expiresAt)) {
    return { accessToken, refreshed: null as null | { accessToken: string; refreshToken?: string; expiresIn: number } };
  }

  if (!refreshToken) {
    throw new Error("Spotify account is not connected");
  }

  const refreshed = await refreshAccessToken({ refreshToken, clientId, clientSecret });
  if (!refreshed.access_token || !refreshed.expires_in) {
    throw new Error("Failed to refresh Spotify token");
  }

  return {
    accessToken: refreshed.access_token,
    refreshed: {
      accessToken: refreshed.access_token,
      refreshToken: refreshed.refresh_token || refreshToken,
      expiresIn: refreshed.expires_in,
    },
  };
}

async function spotifyFetch<T>(accessToken: string, url: string, init?: RequestInit): Promise<T> {
  const res = await fetch(url, {
    ...init,
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
      ...(init?.headers || {}),
    },
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error(`Spotify request failed (${res.status})`);
  }

  return (await res.json()) as T;
}

export async function POST(req: NextRequest) {
  let payload: CreatePlaylistBody | null = null;
  try {
    payload = (await req.json()) as CreatePlaylistBody;
    const trackUrls = Array.isArray(payload.trackUrls) ? payload.trackUrls : [];

    const uris = Array.from(
      new Set(trackUrls.map(extractSpotifyTrackUri).filter((uri): uri is string => Boolean(uri))),
    );

    if (!uris.length) {
      await writeApiLogFile({
        route: "/api/spotify/create-playlist",
        level: "warn",
        event: "NO_VALID_TRACKS",
        context: {
          trackUrlCount: trackUrls.length,
          payload,
        },
      });
      return NextResponse.json({ error: "No valid Spotify tracks provided" }, { status: 400 });
    }

    const { accessToken, refreshed } = await getValidAccessToken(req);

    const me = await spotifyFetch<{ id: string }>(accessToken, "https://api.spotify.com/v1/me");

    const createdPlaylist = await spotifyFetch<{
      id: string;
      external_urls?: { spotify?: string };
    }>(accessToken, `https://api.spotify.com/v1/users/${me.id}/playlists`, {
      method: "POST",
      body: JSON.stringify({
        name: payload.name || "AI Playlist",
        description: payload.description || "Generated by AI Playlist Builder",
        public: Boolean(payload.isPublic),
      }),
    });

    for (let i = 0; i < uris.length; i += 100) {
      const chunk = uris.slice(i, i + 100);
      await spotifyFetch(accessToken, `https://api.spotify.com/v1/playlists/${createdPlaylist.id}/tracks`, {
        method: "POST",
        body: JSON.stringify({ uris: chunk }),
      });
    }

    const response = NextResponse.json({
      playlistId: createdPlaylist.id,
      playlistUrl: createdPlaylist.external_urls?.spotify || `https://open.spotify.com/playlist/${createdPlaylist.id}`,
      playlistUri: `spotify:playlist:${createdPlaylist.id}`,
      tracksAdded: uris.length,
    });

    if (refreshed) {
      setTokenCookies(response, refreshed);
    }

    return response;
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to create playlist";
    const status = message.includes("not connected") ? 401 : 500;
    await writeApiLogFile({
      route: "/api/spotify/create-playlist",
      level: "error",
      event: "CREATE_PLAYLIST_ERROR",
      error,
      context: {
        payload,
      },
    });
    return NextResponse.json({ error: message }, { status });
  }
}
